name: Build, Lint, and Deploy to Docker Hub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Continuous-Integration:
    name: Lint and Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

  Build-and-Push-Docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: Continuous-Integration
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/your-repo-name:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push your-dockerhub-username/your-repo-name:latest
